### ISSUE TITLE
my single a100 only can raise four 7b llms, how can i raise more llms with one gpu?

### ISSUE THREAD

**Issue by fuxuelinwudi** [yaoching0/GaC#1]
can author provide some lower gpu utilize methods?

**Comment by yaoching0** [comment]
> can author provide some lower gpu utilize methods?

Hi! I‘m very sorry for the delayed response..

Thank you for your suggestion. I have tried to support quantization (See [PR](https://github.com/yaoching0/GaC/pull/4)). Now you only need to add `quantization` to the config and set it as needed to `'none'`, `'8bit'`, or `'4bit'`.

Example:

```yaml
NORM_TYPE_API_SERVER: 'average' # 'average' or 'score'
THRESHOLD_API_SERVER: 1.0
CONFIG_API_SERVER:
  - weight: '[Please replace with the path to the local model weight]' # or 'upstage/SOLAR-10.7B-Instruct-v1.0'
    max_memory:
      0: '24GiB'
    num_gpus: 0.5
    name: 'SOLAR-10.7B-Instruct-v1.0'
    score: 100
    priority: 'supportive' # 'primary' or 'supportive'
    quantization: 'none' # 'none'/'8bit'/'4bit'    <-------------------------- Here
```

This way, you can control the quantization level of each model participating in the ensemble.

If you have any questions, feel free to contact~
